version: "3"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: 123
    ports:
    - "5432:5432"

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: 123
    ports:
    - "3306:3306"